# Generated by Django 6.1 on 2026-08-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, default='', max_length=200, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Correo Electrónico de Contacto')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono Principal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Taller / Sucursal')),
                ('codigo_sucursal', models.CharField(blank=True, default='001', max_length=10, verbose_name='Código de Sucursal (SRI / Contífico)')),
                ('direccion', models.TextField(verbose_name='Dirección Físicas')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono Taller')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='empresas.empresa', verbose_name='Empresa Perteneciente')),
            ],
            options={
                'verbose_name': 'Taller / Sucursal',
                'verbose_name_plural': 'Talleres / Sucursales',
            },
        ),
    ]
