# Generated by Django 6.1 on 2026-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa_logos/', verbose_name='Logo / Imagen de Empresa'),
        ),
    ]
