# Generated by Django 6.1 on 2026-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
    ]
