# Generated by Django 6.1 on 2026-09-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_taller_ciudad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taller',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('empresa', 'codigo_sucursal'), name='una_sucursal_activa_por_empresa_codigo'),
        ),
    ]
