# Generated by Django 6.1 on 2026-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_taller_una_sucursal_activa_por_empresa_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taller',
            options={'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterField(
            model_name='taller',
            name='codigo_sucursal',
            field=models.CharField(blank=True, default='001', max_length=10, verbose_name='Código de Taller (SRI / Contífico)'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Taller'),
        ),
    ]
