# Generated by Django 6.1 on 2026-09-06 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_taller_options_alter_taller_codigo_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='digitos_cotizacion',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Dígitos de Cotización'),
        ),
        migrations.AddField(
            model_name='taller',
            name='digitos_inspeccion',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Dígitos de Inspección'),
        ),
        migrations.AddField(
            model_name='taller',
            name='digitos_ot',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Dígitos de OT'),
        ),
        migrations.AddField(
            model_name='taller',
            name='digitos_recepcion',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Dígitos de Recepción'),
        ),
        migrations.AddField(
            model_name='taller',
            name='prefijo_cotizacion',
            field=models.CharField(blank=True, default='COT-', max_length=10, verbose_name='Prefijo Cotizaciones'),
        ),
        migrations.AddField(
            model_name='taller',
            name='prefijo_inspeccion',
            field=models.CharField(blank=True, default='INS-', max_length=10, verbose_name='Prefijo Inspecciones'),
        ),
        migrations.AddField(
            model_name='taller',
            name='prefijo_ot',
            field=models.CharField(blank=True, default='OT-', max_length=10, verbose_name='Prefijo Órdenes de Trabajo'),
        ),
        migrations.AddField(
            model_name='taller',
            name='prefijo_recepcion',
            field=models.CharField(blank=True, default='REC-', max_length=10, verbose_name='Prefijo Recepciones'),
        ),
        migrations.AddField(
            model_name='taller',
            name='siguiente_cotizacion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Siguiente número de Cotización'),
        ),
        migrations.AddField(
            model_name='taller',
            name='siguiente_inspeccion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Siguiente número de Inspección'),
        ),
        migrations.AddField(
            model_name='taller',
            name='siguiente_ot',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Siguiente número de OT'),
        ),
        migrations.AddField(
            model_name='taller',
            name='siguiente_recepcion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Siguiente número de Recepción'),
        ),
    ]
