# Generated by Django 6.1 on 2026-09-30 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='capacidad_citas_dia',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de citas que el taller puede recibir en un día. 0 = sin límite.', verbose_name='Citas máximas por día'),
        ),
        migrations.AddField(
            model_name='taller',
            name='capacidad_simultanea',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de vehículos que pueden estar atendiéndose al mismo tiempo (citas en curso y vehículos ya ingresados al taller). 0 = sin límite.', verbose_name='Atenciones simultáneas máximas'),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Inicio del horario en el que se pueden agendar citas.', verbose_name='Hora de apertura'),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Fin del horario en el que se pueden agendar citas.', verbose_name='Hora de cierre'),
        ),
        migrations.AddConstraint(
            model_name='taller',
            constraint=models.CheckConstraint(condition=models.Q(('hora_cierre__gt', models.F('hora_apertura'))), name='taller_horario_atencion_valido'),
        ),
    ]
