# Generated by Django 6.1 on 2026-09-08 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('intervalo_km', models.PositiveIntegerField(default=5000, help_text='Kilometraje máximo sugerido entre mantenimientos preventivos.', verbose_name='Intervalo de mantenimiento (km)')),
                ('dias_antelacion', models.PositiveIntegerField(default=7, help_text='Días antes de la fecha límite en que se envía el recordatorio.', verbose_name='Antelación (días)')),
                ('frecuencia_dias', models.PositiveIntegerField(default=30, help_text='Evita reenviar recordatorio al mismo vehículo antes de este número de días.', verbose_name='Reintento (días)')),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Si está desactivado, el proceso automático no envía recordatorios.', verbose_name='Notificaciones activas')),
                ('notificar_vehiculos_sin_programar', models.BooleanField(default=False, help_text='Incluye vehículos que aún no tienen próximo mantenimiento (km/fecha) configurado.', verbose_name='Notificar sin próximo mantenimiento registrado')),
                ('mensaje_plantilla', models.TextField(default='Hola {cliente}, el taller {empresa} quiere recordarte que tu vehiculo {marca} {modelo} (placa {placa}) esta proximo a su mantenimiento preventivo. Te esperamos para que lo revises a tiempo. Respondenos este mensaje para agendar tu cita. Gracias.', help_text='Placeholders disponibles: {cliente}, {empresa}, {marca}, {modelo}, {placa}, {kilometraje}.', verbose_name='Plantilla del mensaje')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_mantenimiento', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Preferencia de mantenimiento',
                'verbose_name_plural': 'Preferencias de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='RegistroMensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente')),
                ('celular', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('mensaje', models.TextField(blank=True, default='', verbose_name='Mensaje')),
                ('canal', models.CharField(default='whatsapp', max_length=20, verbose_name='Canal')),
                ('proveedor', models.CharField(default='mock', help_text='mock, twilio_sandbox o meta_api.', max_length=30, verbose_name='Proveedor usado')),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('SIMULADO', 'Simulado (entorno de prueba)')], default='SIMULADO', max_length=20, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual desde la interfaz'), ('PROGRAMADO', 'Proceso automático'), ('PRUEBA', 'Mensaje de prueba')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('id_externo', models.CharField(blank=True, default='', help_text='SID de Twilio o ID de mensaje de Meta Cloud API.', max_length=100, verbose_name='ID externo (proveedor)')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('metadatos', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_whatsapp', to='empresas.empresa', verbose_name='Empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_whatsapp', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Registro de mensaje WhatsApp',
                'verbose_name_plural': 'Registros de mensajes WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
