# Generated by Django 6.1 on 2026-09-08 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
        ('ordenes', '0029_alter_detallerepuestoinspeccion_es_sugerido_and_more'),
        ('vehiculos', '0007_update_imagen_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la cita')),
                ('fecha_hora_programada', models.DateTimeField(blank=True, help_text='Se resuelve automáticamente a partir de fecha_cita + hora_cita.', null=True, verbose_name='Fecha y hora programada')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('motivo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento Preventivo'), ('REPARACION', 'Reparación / Falla Reportada'), ('DIAGNOSTICO', 'Diagnóstico / Escaneo'), ('ESTETICA', 'Enderezada, Pintura o Detailing'), ('GARANTIA', 'Garantía / Retorno'), ('OTRO', 'Otro')], default='MANTENIMIENTO', max_length=20, verbose_name='Motivo')),
                ('motivo_descripcion', models.TextField(blank=True, help_text='Detalle de la falla o servicio solicitado por el cliente', null=True, verbose_name='Descripción del motivo')),
                ('kilometraje_aproximado', models.PositiveIntegerField(blank=True, help_text='Kilometraje reportado por el cliente al agendar', null=True, verbose_name='Kilometraje aproximado')),
                ('fecha_conversion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conversión a recepción')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones para el equipo del taller (no visibles para el cliente)', null=True, verbose_name='Notas internas')),
                ('asesor', models.ForeignKey(blank=True, help_text='Asesor o recepcionista que atiende la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='empresas.empresa', verbose_name='Empresa')),
                ('recepcion_generada', models.ForeignKey(blank=True, help_text='Recepción de vehículo creada a partir de esta cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='ordenes.recepcionvehiculo', verbose_name='Recepción generada')),
                ('taller', models.ForeignKey(blank=True, help_text='Taller donde se atenderá la cita (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='empresas.taller', verbose_name='Taller')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_cita', '-hora_cita'],
            },
        ),
    ]
