# Generated by Django 6.1 on 2026-09-30 03:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('clientes', '0005_alter_cliente_identificacion'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
        ('ordenes', '0042_detallerepuestoordentrabajo_descuento_and_more'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración estimada de la cita; define el espacio que ocupa en la agenda.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)], verbose_name='Duración (minutos)'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['empresa', 'fecha_cita'], name='cita_empresa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['taller', 'fecha_cita'], name='cita_taller_fecha_idx'),
        ),
    ]
