# Generated by Django 6.0.5 on 2026-05-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de activo',
                'verbose_name_plural': 'Tipos de activos',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.client', verbose_name='Cliente')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assettype', verbose_name='Tipo de activo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('service_date', models.DateField(verbose_name='Fecha del servicio')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('technician_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnico responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(verbose_name='Fecha del recordatorio')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
            },
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_photos/', verbose_name='Imagen')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Foto del servicio',
                'verbose_name_plural': 'Fotos del servicio',
            },
        ),
    ]
