# Generated by Django 6.0.5 on 2026-05-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assettype_alter_client_options_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='installation_date',
        ),
    ]
