# Generated by Django 6.1 on 2026-08-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_asset_installation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='client',
        ),
        migrations.RemoveField(
            model_name='service',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='service',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServicePhoto',
        ),
    ]
