# Generated by Django 6.1 on 2026-09-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('tipo_identificacion', models.CharField(choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte')], default='R', max_length=1, verbose_name='Tipo de Identificación')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación (Cédula/RUC/Pasaporte)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, default='', max_length=150, verbose_name='Persona de Contacto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'identificacion'), name='unique_proveedor_per_empresa')],
            },
        ),
    ]
