# Generated by Django 6.1 on 2026-08-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('ordenes', '0002_alter_ordentrabajo_cotizacion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='orden_trabajo_origen',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo de la cual surgió este presupuesto tras un diagnóstico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_generadas', to='ordenes.ordentrabajo'),
        ),
    ]
