# Generated by Django 6.1 on 2026-08-28 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_orden_trabajo_origen'),
        ('ordenes', '0004_alter_recepcionvehiculo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aceptada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='Aceptada por'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='inspeccion_origen',
            field=models.ForeignKey(blank=True, help_text='Inspección técnica de la cual se derivó esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_generadas', to='ordenes.inspeccionvehiculo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='metodo_aceptacion',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial en taller'), ('EMAIL', 'Correo electrónico'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono')], max_length=20, null=True, verbose_name='Método de aceptación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='recepcion_origen',
            field=models.ForeignKey(blank=True, help_text='Recepción del vehículo de la cual se derivó esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_generadas', to='ordenes.recepcionvehiculo'),
        ),
    ]
