# Generated by Django 6.1 on 2026-09-06 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('cotizaciones', '0003_cotizacion_aceptada_por_cotizacion_fecha_aceptacion_and_more'),
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
        ('ordenes', '0022_detallerepuestoinspeccion_detalleservicioinspeccion'),
        ('vehiculos', '0007_update_imagen_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Taller que emite la cotización (secuencia de numeración)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='empresas.taller', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(max_length=20, verbose_name='Número de Cotización'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_cotizacion'), name='cotizacion_empresa_numero_unico'),
        ),
    ]
