# Generated by Django 6.1 on 2026-09-06 05:02

from django.db import migrations


def asignar_sucursal(apps, schema_editor):
    """Vincula las cotizaciones existentes sin taller al taller por defecto de su empresa.

    No se regenera `numero_cotizacion` existente; el número secuencial ya se asigna
    automáticamente en la creación (los registros previos conservan su número).
    """
    Taller = apps.get_model('empresas', 'Taller')
    Cotizacion = apps.get_model('cotizaciones', 'Cotizacion')

    for cotizacion in Cotizacion.objects.filter(sucursal__isnull=True):
        taller = None
        if cotizacion.recepcion_origen_id and cotizacion.recepcion_origen.sucursal_id:
            taller = Taller.objects.filter(pk=cotizacion.recepcion_origen.sucursal_id, is_active=True).first()
        if taller is None and cotizacion.empresa_id:
            taller = (
                Taller.objects.filter(empresa_id=cotizacion.empresa_id, is_active=True)
                .order_by('id')
                .first()
            )
        if taller:
            cotizacion.sucursal = taller
            cotizacion.save(update_fields=['sucursal'])


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_sucursal_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_sucursal, reverse_code=migrations.RunPython.noop),
    ]