# Generated by Django 6.1 on 2026-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_cotizacion_cotizacion_inspeccion_vigente_unica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
    ]
