# Generated by Django 6.1 on 2026-09-28 16:38

from decimal import Decimal
from django.db import migrations, models

DOS = Decimal('0.01')


def backfill_impuestos_cotizaciones(apps, schema_editor):
    """Recalcula las cotizaciones existentes con el esquema de impuestos por línea.

    - Cada línea queda con `monto_iva` calculado con su porcentaje
      (15% uniforme histórico).
    - Las cabeceras se recomputan con la fórmula nueva (bases 0%/15%).
    """
    Cotizacion = apps.get_model('cotizaciones', 'Cotizacion')

    for cotizacion in Cotizacion.objects.all():
        servicios = list(cotizacion.servicios.all())
        repuestos = list(cotizacion.repuestos.all())
        lineas = servicios + repuestos

        for det in lineas:
            det.monto_iva = (det.subtotal * det.iva_porcentaje).quantize(DOS)
            det.save(update_fields=['monto_iva'])

        neto_serv = sum(det.subtotal for det in servicios)
        neto_rep = sum(det.subtotal for det in repuestos)
        cotizacion.subtotal_servicios = neto_serv
        cotizacion.subtotal_repuestos = neto_rep
        cotizacion.descuento = sum(det.descuento for det in lineas)
        cotizacion.subtotal_neto = neto_serv + neto_rep
        cotizacion.subtotal_base_0 = sum(
            det.subtotal for det in lineas if det.iva_porcentaje == 0
        )
        cotizacion.subtotal_base_gravada = sum(
            det.subtotal for det in lineas if det.iva_porcentaje > 0
        )
        cotizacion.subtotal = cotizacion.subtotal_neto + cotizacion.descuento
        cotizacion.total_iva = sum(det.monto_iva for det in lineas)
        cotizacion.total = cotizacion.subtotal_neto + cotizacion.total_iva
        cotizacion.save(update_fields=[
            'subtotal_servicios', 'subtotal_repuestos', 'descuento', 'subtotal_neto',
            'subtotal_base_0', 'subtotal_base_gravada', 'subtotal', 'total_iva', 'total',
            'updated_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_cotizacion_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_base_0',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_base_gravada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_neto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_repuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_servicios',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerepuestocotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerepuestocotizacion',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detallerepuestocotizacion',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleserviciocotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleserviciocotizacion',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleserviciocotizacion',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal bruto acumulado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto total del IVA'),
        ),
        migrations.AlterField(
            model_name='detallerepuestocotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Representa el NETO de la línea', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleserviciocotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Representa el NETO de la línea', max_digits=10),
        ),
        migrations.RunPython(backfill_impuestos_cotizaciones, migrations.RunPython.noop),
    ]
