# Generated by Django 6.1 on 2026-10-01 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('cotizaciones', '0011_cotizacion_descuento_cotizacion_subtotal_base_0_and_more'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
        ('ordenes', '0043_remove_ordentrabajo_observaciones_internas'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cotizacion',
            name='cotizacion_inspeccion_vigente_unica',
        ),
        migrations.RemoveConstraint(
            model_name='cotizacion',
            name='cotizacion_recepcion_vigente_unica',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada al Cliente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CONVERTIDA', 'Convertida a Orden')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENVIADA', 'ACEPTADA'])), fields=('inspeccion_origen',), name='cotizacion_inspeccion_vigente_unica'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENVIADA', 'ACEPTADA'])), fields=('recepcion_origen',), name='cotizacion_recepcion_vigente_unica'),
        ),
    ]
