# Generated by Django 6.1 on 2026-10-01 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_remove_cotizacion_cotizacion_inspeccion_vigente_unica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='asesor',
            field=models.ForeignKey(blank=True, help_text='Asesor o recepcionista a cargo de la atención de la cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_asesoradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
