# Generated by Django 6.1 on 2026-10-04 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('cotizaciones', '0016_allow_multiple_quotes_per_origin'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
        ('ordenes', '0043_remove_ordentrabajo_observaciones_internas'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cotizacion',
            name='cotizacion_empresa_numero_unico',
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'numero_cotizacion'), name='cotizacion_empresa_sucursal_numero_unico'),
        ),
    ]
