# Generated by Django 6.1 on 2026-08-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('rol', models.CharField(choices=[('ADMIN_SISTEMA', 'Superadmin SaaS'), ('ADMIN_EMPRESA', 'Dueño / Admin de Empresa'), ('ADMIN_TALLER', 'Gerente de Taller'), ('ASESOR', 'Asesor de Servicio'), ('MECANICO', 'Técnico / Mecánico'), ('CAJERO', 'Caja / Facturación')], default='MECANICO', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empresas.empresa')),
                ('taller_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='empresas.taller', verbose_name='Taller Activo en Sesión')),
                ('talleres', models.ManyToManyField(blank=True, related_name='usuarios', to='empresas.taller', verbose_name='Talleres Asignados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
