# Generated by Django 6.1 on 2026-08-20 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('empresas', '0002_empresa_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='talleres',
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('rol', models.CharField(choices=[('ADMIN_SISTEMA', 'Superadmin SaaS'), ('ADMIN_EMPRESA', 'Dueño / Admin de Empresa'), ('ADMIN_TALLER', 'Gerente de Taller'), ('ASESOR', 'Asesor de Servicio'), ('MECANICO', 'Técnico / Mecánico'), ('CAJERO', 'Caja / Facturación')], default='MECANICO', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Acceso Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asociados', to='empresas.empresa')),
                ('talleres', models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='empresas.taller', verbose_name='Talleres Asignados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_asociadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Usuario-Empresa',
                'verbose_name_plural': 'Asignaciones Usuarios-Empresas',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
