# Generated by Django 6.1 on 2026-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_empresa_remove_userprofile_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='Identificación (Cédula/RUC/Pasaporte)'),
        ),
    ]
