# Generated by Django 6.1 on 2026-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
    ]
