# Generated by Django 6.1 on 2026-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/avatares/', verbose_name='Foto de perfil'),
        ),
    ]
