# Generated by Django 6.1 on 2026-10-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_backfill_talleres_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='tiene_acceso',
            field=models.BooleanField(default=True, help_text='Si se desactiva, la persona existe como empleado pero no puede iniciar sesión.', verbose_name='¿Tiene acceso al sistema?'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN_SISTEMA', 'Superadmin SaaS'), ('ADMIN_EMPRESA', 'Dueño / Admin de Empresa'), ('ADMIN_TALLER', 'Gerente de Taller'), ('ASESOR', 'Asesor de Servicio'), ('MECANICO', 'Técnico / Mecánico'), ('CAJERO', 'Caja / Facturación')], default='MECANICO', help_text='Solo aplica si el empleado tiene acceso al sistema.', max_length=20, null=True, verbose_name='Rol'),
        ),
    ]
