# Generated by Django 6.1 on 2026-10-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_usuarioempresa_tiene_acceso_alter_usuarioempresa_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_SISTEMA', 'Superadmin SaaS'), ('ADMIN_EMPRESA', 'Dueño / Admin de Empresa'), ('ADMIN_TALLER', 'Gerente de Taller'), ('ASESOR', 'Asesor de Servicio'), ('MECANICO', 'Técnico / Mecánico'), ('CAJERO', 'Caja / Facturación')], max_length=20, verbose_name='Rol')),
                ('recurso', models.CharField(max_length=50, verbose_name='Recurso')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
                'unique_together': {('rol', 'recurso', 'accion')},
            },
        ),
    ]
