# Generated by Django 6.1 on 2026-10-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rolpermiso'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='rol',
            field=models.CharField(blank=True, default='MECANICO', help_text='Código del rol (sistema o personalizado de la empresa). Solo aplica si el empleado tiene acceso al sistema.', max_length=50, null=True, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('MODULO', 'Módulo'), ('FUNCIONALIDAD', 'Funcionalidad')], default='MODULO', max_length=20, verbose_name='Tipo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='authentication.recurso', verbose_name='Recurso padre')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AccionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_especiales', to='authentication.recurso', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Acción especial',
                'verbose_name_plural': 'Acciones especiales',
                'ordering': ['recurso__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('codigo', models.CharField(help_text='Identificador estable del rol (los de sistema conservan sus códigos históricos).', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('es_sistema', models.BooleanField(default=False, verbose_name='Rol del sistema')),
                ('nivel', models.PositiveIntegerField(default=1, verbose_name='Nivel jerárquico')),
                ('ver_todos_talleres', models.BooleanField(default=False, verbose_name='Ver todos los talleres')),
                ('empresa', models.ForeignKey(blank=True, help_text='Solo los roles personalizados pertenecen a una empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='empresas.empresa', verbose_name='Empresa propietaria')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['es_sistema', 'nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PermisoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authentication.accionespecial', verbose_name='Acción especial')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales', to='authentication.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso especial de rol',
                'verbose_name_plural': 'Permisos especiales de roles',
                'unique_together': {('rol', 'accion')},
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('ver', models.BooleanField(default=False, verbose_name='Ver')),
                ('modificar', models.BooleanField(default=False, verbose_name='Modificar')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='authentication.recurso', verbose_name='Recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='authentication.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
                'unique_together': {('rol', 'recurso')},
            },
        ),
    ]
