# Generated by Django 6.1 on 2026-10-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_roles_personalizados'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('ver', models.BooleanField(default=False, verbose_name='Ver')),
                ('modificar', models.BooleanField(default=False, verbose_name='Modificar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_overrides', to='empresas.empresa', verbose_name='Empresa')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_empresa', to='authentication.recurso', verbose_name='Recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_empresa', to='authentication.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol por empresa',
                'verbose_name_plural': 'Permisos de roles por empresa',
                'unique_together': {('empresa', 'rol', 'recurso')},
            },
        ),
        migrations.CreateModel(
            name='PermisoEspecialEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('permitido', models.BooleanField(default=True, verbose_name='Permitido')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_empresa', to='authentication.accionespecial', verbose_name='Acción especial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales_overrides', to='empresas.empresa', verbose_name='Empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales_empresa', to='authentication.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso especial de rol por empresa',
                'verbose_name_plural': 'Permisos especiales de roles por empresa',
                'unique_together': {('empresa', 'rol', 'accion')},
            },
        ),
    ]
