# Generated by Django 6.1 on 2026-10-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_borrar_catalogo_acciones_especiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolpermiso',
            name='rol',
            field=models.CharField(choices=[('ADMIN_SISTEMA', 'Superadmin SaaS'), ('ADMIN_EMPRESA', 'Administrador'), ('ADMIN_TALLER', 'Jefe de Taller'), ('ASESOR', 'Asesor'), ('MECANICO', 'Mecánico'), ('CAJERO', 'Cajero')], max_length=20, verbose_name='Rol'),
        ),
    ]
