# Generated by Django 6.1 on 2026-08-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('tipo_identificacion', models.CharField(choices=[('C', 'Cédula'), ('R', 'RUC'), ('P', 'Pasaporte')], default='C', max_length=1, verbose_name='Tipo de Identificación')),
                ('identificacion', models.CharField(max_length=13, unique=True, verbose_name='Identificación (Cédula/RUC/Pasaporte)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('contifico_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID de Integración Contífico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
