# Generated by Django 6.1 on 2026-08-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_empresa'),
        ('empresas', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'identificacion'), name='unique_cliente_per_empresa'),
        ),
    ]
