# Generated by Django 6.1 on 2026-08-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_unique_cliente_per_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Identificación (Cédula/RUC/Pasaporte)'),
        ),
    ]
