# Generated by Django 6.1 on 2026-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, verbose_name='Identificación (Cédula/RUC/Pasaporte)'),
        ),
    ]
