# Generated by Django 6.1 on 2026-09-05 23:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_alter_taller_options_alter_taller_codigo_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del repuesto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del repuesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('FILTROS', 'Filtros'), ('ACEITES', 'Aceites y Lubricantes'), ('FRENOS', 'Sistema de Frenos'), ('MOTOR', 'Motor'), ('ELECTRICO', 'Sistema Eléctrico'), ('SUSPENSION', 'Suspensión y Dirección'), ('TRANSMISION', 'Transmisión'), ('CARROCERIA', 'Carrocería'), ('ILUMINACION', 'Iluminación'), ('REFRIGERACION', 'Refrigeración'), ('OTROS', 'Otros')], default='OTROS', max_length=30, verbose_name='Categoría')),
                ('marca', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca / Fabricante')),
                ('numero_parte', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de parte original')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('LITRO', 'Litro'), ('GALON', 'Galón'), ('KG', 'Kilogramo'), ('METRO', 'Metro')], default='UNIDAD', max_length=10, verbose_name='Unidad de medida')),
                ('costo_referencial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo referencial (compra)')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de venta sugerido (sin IVA)')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Sujeto a IVA')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Por debajo de este valor el repuesto se marca como stock bajo', max_digits=10, verbose_name='Stock mínimo')),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100, verbose_name='Ubicación / Estante / Bodega')),
                ('proveedor', models.CharField(blank=True, default='', max_length=150, verbose_name='Proveedor habitual')),
                ('contifico_producto_id', models.CharField(blank=True, help_text='Código del producto en el sistema contable Contífico (integración)', max_length=100, null=True, verbose_name='ID de producto en Contífico')),
                ('contifico_cuenta_contable', models.CharField(blank=True, help_text='Código de la cuenta contable asociada en Contífico (integración)', max_length=50, null=True, verbose_name='Cuenta contable Contífico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='empresas.empresa')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Taller donde se almacena o comercializa el repuesto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos', to='empresas.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('empresa', 'codigo'), name='repuesto_codigo_activo_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del servicio')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('MECANICA', 'Mecánica General'), ('ELECTRICO', 'Eléctrico / Electrónica'), ('MANTENIMIENTO', 'Mantenimiento Preventivo'), ('DIAGNOSTICO', 'Diagnóstico / Escaneo'), ('ENDEREZADA', 'Enderezada / Pintura'), ('GARANTIA', 'Garantía')], default='MECANICA', max_length=30, verbose_name='Categoría')),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(default=60, help_text='Tiempo estándar estimado para ejecutar la tarea', verbose_name='Tiempo estimado (minutos)')),
                ('tareas_estandar', models.TextField(blank=True, help_text='Detalle de las actividades que incluye el servicio', null=True, verbose_name='Tareas estándar incluidas')),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio referencial de mano de obra')),
                ('contifico_producto_id', models.CharField(blank=True, help_text='Código del servicio en el sistema contable Contífico (integración)', max_length=100, null=True, verbose_name='ID de producto/servicio en Contífico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_catalogo', to='empresas.empresa')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Taller donde se presta el servicio (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_catalogo', to='empresas.taller', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Servicio (Mano de Obra)',
                'verbose_name_plural': 'Servicios (Mano de Obra)',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('empresa', 'codigo'), name='servicio_codigo_activo_por_empresa')],
            },
        ),
    ]
