# Generated by Django 6.1 on 2026-09-28 16:38

from decimal import Decimal
from django.db import migrations, models


def aplica_iva_a_porcentaje(apps, schema_editor):
    """Preserva la exención histórica: repuestos marcados sin IVA quedan a 0%."""
    Repuesto = apps.get_model('inventario', 'Repuesto')
    Repuesto.objects.filter(aplica_iva=False).update(
        iva_porcentaje_defecto=Decimal('0.0000')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='iva_porcentaje_defecto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, verbose_name='Porcentaje de IVA por defecto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='iva_porcentaje_defecto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5, verbose_name='Porcentaje de IVA por defecto'),
        ),
        migrations.RunPython(aplica_iva_a_porcentaje, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='repuesto',
            name='aplica_iva',
        ),
    ]
