# Generated by Django 6.1 on 2026-08-17 00:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_empresa'),
        ('cotizaciones', '0001_initial'),
        ('empresas', '0001_initial'),
        ('vehiculos', '0002_remove_vehiculo_tipo_combustible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='Número de OT')),
                ('estado', models.CharField(choices=[('INGRESADO', 'En Recepción / Diagnóstico'), ('EN_PROCESO', 'En Trabajo / Ejecución'), ('COMPLETADO', 'Trabajo Listo'), ('ENTREGADO', 'Entregado y Cerrado'), ('CANCELADO', 'Anulado / Cancelado')], default='INGRESADO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente / Emergencia')], default='MEDIA', max_length=10)),
                ('tipo_trabajo', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Reparación Correctiva'), ('DIAGNOSTICO', 'Solo Diagnóstico / Escaneo'), ('ESTETICA', 'Enderezada, Pintura o Detailing'), ('GARANTIA', 'Garantía / Retorno')], default='PREVENTIVO', max_length=20)),
                ('kilometraje_ingreso', models.PositiveIntegerField(verbose_name='Kilometraje de Ingreso')),
                ('nivel_combustible', models.CharField(choices=[('RESERVA', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('LLENO', 'Lleno')], default='1/4', max_length=10)),
                ('falla_reportada', models.TextField(verbose_name='Síntomas o Falla Reportada por el Cliente')),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Realizado por el Mecánico')),
                ('observaciones_internas', models.TextField(blank=True, help_text='Notas no visibles para el cliente', null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_repuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('asesor', models.ForeignKey(blank=True, help_text='Asesor o recepcionista a cargo de la atención', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asesoradas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='clientes.cliente')),
                ('cotizacion_origen', models.OneToOneField(blank=True, help_text='Cotización previa de la cual se derivó esta orden (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_trabajo', to='cotizaciones.cotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='empresas.empresa')),
                ('mecanico_principal', models.ForeignKey(blank=True, help_text='Mecánico o técnico responsable de la reparación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionVehiculo',
            fields=[
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recepcion', serialize=False, to='ordenes.ordentrabajo')),
                ('ingreso_en_grua', models.BooleanField(default=False, verbose_name='¿Ingresó en grúa?')),
                ('datos_grua', models.CharField(blank=True, max_length=150, null=True, verbose_name='Datos de la grúa / Chófer')),
                ('tiene_radio', models.BooleanField(default=True, verbose_name='Radio / Mascarilla')),
                ('tiene_llanta_repuesto', models.BooleanField(default=True, verbose_name='Llanta de Repuesto')),
                ('tiene_gata_palanca', models.BooleanField(default=True, verbose_name='Gata y Palanca')),
                ('tiene_extintor', models.BooleanField(default=False, verbose_name='Extintor')),
                ('tiene_botiquin', models.BooleanField(default=False, verbose_name='Botiquín')),
                ('tiene_antena', models.BooleanField(default=True, verbose_name='Antena')),
                ('tiene_copas_ruedas', models.BooleanField(default=True, verbose_name='Copas / Tapacubos')),
                ('tiene_herramientas', models.BooleanField(default=False, verbose_name='Juego de Herramientas')),
                ('testigo_check_engine', models.BooleanField(default=False, verbose_name='Check Engine')),
                ('testigo_abs', models.BooleanField(default=False, verbose_name='ABS')),
                ('testigo_airbag', models.BooleanField(default=False, verbose_name='Airbag')),
                ('testigo_bateria', models.BooleanField(default=False, verbose_name='Batería')),
                ('testigo_aceite', models.BooleanField(default=False, verbose_name='Presión de Aceite')),
                ('otros_testigos_observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros Testigos u Observaciones del Tablero')),
                ('detalles_carroceria', models.TextField(blank=True, null=True, verbose_name='Descripción de Golpes, Rayones o Estado de Pintura')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicioOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Servicio')),
                ('horas_aplicadas', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completado', models.BooleanField(default=False)),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico que ejecutó el servicio')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ordenes.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRepuestoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_repuesto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Repuesto')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contifico_producto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='ordenes.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/recepcion_fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ej: Rayón puerta izquierda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.recepcionvehiculo')),
            ],
        ),
    ]
