# Generated by Django 6.1 on 2026-08-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, help_text='Cotización que dio origen o autorizó los trabajos de esta OT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_derivadas', to='cotizaciones.cotizacion'),
        ),
    ]
