# Generated by Django 6.1 on 2026-08-23 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_orden_trabajo_origen'),
        ('ordenes', '0002_alter_ordentrabajo_cotizacion_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cotizacion_origen',
            field=models.OneToOneField(blank=True, help_text='Cotización previa de la cual se derivó esta orden (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_trabajo', to='cotizaciones.cotizacion'),
        ),
    ]
