# Generated by Django 6.1 on 2026-08-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_ordentrabajo_cotizacion_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcionvehiculo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recepción de Vehículo', 'verbose_name_plural': 'Recepciones de Vehículos'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='diagnostico_tecnico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='falla_reportada',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='kilometraje_ingreso',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='nivel_combustible',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='otros_testigos_observaciones',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='testigo_abs',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='testigo_aceite',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='testigo_airbag',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='testigo_bateria',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='testigo_check_engine',
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='kilometraje_ingreso',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje de Ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='nivel_combustible',
            field=models.CharField(choices=[('RESERVA', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('LLENO', 'Lleno')], default='1/4', max_length=10),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación'),
        ),
        migrations.RemoveField(
            model_name='fotorecepcion',
            name='recepcion',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='recepcionvehiculo',
                    name='orden_trabajo',
                ),
                migrations.AddField(
                    model_name='recepcionvehiculo',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AddField(
                    model_name='recepcionvehiculo',
                    name='orden_trabajo',
                    field=models.ForeignKey(blank=True, help_text='Orden de trabajo asociada (si ya fue generada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='ordenes.ordentrabajo'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE ordenes_recepcionvehiculo DROP CONSTRAINT ordenes_recepcionvehiculo_pkey;",
                        "ALTER TABLE ordenes_recepcionvehiculo ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;",
                        "ALTER TABLE ordenes_recepcionvehiculo ALTER COLUMN orden_trabajo_id DROP NOT NULL;",
                    ],
                    reverse_sql=[
                        "ALTER TABLE ordenes_recepcionvehiculo DROP CONSTRAINT ordenes_recepcionvehiculo_pkey;",
                        "ALTER TABLE ordenes_recepcionvehiculo DROP COLUMN id;",
                        "ALTER TABLE ordenes_recepcionvehiculo ALTER COLUMN orden_trabajo_id SET NOT NULL;",
                        "ALTER TABLE ordenes_recepcionvehiculo ADD CONSTRAINT ordenes_recepcionvehiculo_pkey PRIMARY KEY (orden_trabajo_id);",
                    ],
                ),
            ],
        ),
        migrations.AddField(
            model_name='fotorecepcion',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.recepcionvehiculo'),
        ),
        migrations.CreateModel(
            name='InspeccionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('falla_reportada', models.TextField(verbose_name='Síntomas o Falla Reportada por el Cliente')),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Realizado por el Mecánico')),
                ('testigo_check_engine', models.BooleanField(default=False, verbose_name='Check Engine')),
                ('testigo_abs', models.BooleanField(default=False, verbose_name='ABS')),
                ('testigo_airbag', models.BooleanField(default=False, verbose_name='Airbag')),
                ('testigo_bateria', models.BooleanField(default=False, verbose_name='Batería')),
                ('testigo_aceite', models.BooleanField(default=False, verbose_name='Presión de Aceite')),
                ('otros_testigos_observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros Testigos u Observaciones del Tablero')),
                ('orden_trabajo', models.OneToOneField(blank=True, help_text='Orden de trabajo asociada (si ya fue generada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspeccion', to='ordenes.ordentrabajo')),
                ('recepcion', models.ForeignKey(blank=True, help_text='Recepción del vehículo de la cual se derivó esta inspección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='ordenes.recepcionvehiculo')),
            ],
            options={
                'verbose_name': 'Inspección de Vehículo',
                'verbose_name_plural': 'Inspecciones de Vehículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
