# Generated by Django 6.1 on 2026-08-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('ordenes', '0004_alter_recepcionvehiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='empresas.empresa'),
        ),
    ]
