# Generated by Django 6.1 on 2026-08-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_identificacion'),
        ('ordenes', '0006_recepcionvehiculo_cliente_recepcionvehiculo_vehiculo'),
        ('vehiculos', '0007_update_imagen_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='vehiculos.vehiculo'),
        ),
    ]
