# Generated by Django 6.1 on 2026-08-28 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_alter_recepcionvehiculo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='datos_danos_carroceria',
            field=models.JSONField(blank=True, help_text='Puntos de daños marcados sobre el gráfico del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso al Taller'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Salida del Taller'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_cargador_celular',
            field=models.BooleanField(default=False, verbose_name='Cargador de Celular'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_control_puertas',
            field=models.BooleanField(default=False, verbose_name='Control de Puertas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_cubresol',
            field=models.BooleanField(default=False, verbose_name='Cubresol'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_encendedor',
            field=models.BooleanField(default=False, verbose_name='Encendedor'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_espejo_derecho',
            field=models.BooleanField(default=True, verbose_name='Espejo Derecho'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_espejo_izquierdo',
            field=models.BooleanField(default=True, verbose_name='Espejo Izquierdo'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_faros_lunas',
            field=models.BooleanField(default=True, verbose_name='Faros / Lunas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_llave_tuercas',
            field=models.BooleanField(default=False, verbose_name='Llave de Tuercas / Llave de Cruz'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_pantalla',
            field=models.BooleanField(default=False, verbose_name='Pantalla / Multimedia'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_placas',
            field=models.BooleanField(default=True, verbose_name='Placas de Circulación'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_tapa_gasolina',
            field=models.BooleanField(default=True, verbose_name='Tapa de Gasolina'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_tapetes',
            field=models.BooleanField(default=True, verbose_name='Tapetes / Alfombras'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_triangulos',
            field=models.BooleanField(default=False, verbose_name='Triángulos de Seguridad'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_vidrios',
            field=models.BooleanField(default=True, verbose_name='Vidrios / Cristales'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='detalles_carroceria',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones / Descripción de Golpes, Rayones o Estado de Pintura'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='nivel_combustible',
            field=models.CharField(choices=[('VACIO', 'Vacíio'), ('RESERVA', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('LLENO', 'Lleno')], default='1/4', max_length=10),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_gata_palanca',
            field=models.BooleanField(default=True, verbose_name='Gato y Palanca'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_llanta_repuesto',
            field=models.BooleanField(default=True, verbose_name='Llanta de Refacción / Repuesto'),
        ),
    ]
