# Generated by Django 6.1 on 2026-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_recepcionvehiculo_datos_danos_carroceria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='otros_testigos_observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros Testigos u Observaciones del Tablero'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_abs',
            field=models.BooleanField(default=False, verbose_name='ABS'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_aceite',
            field=models.BooleanField(default=False, verbose_name='Presión de Aceite'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_airbag',
            field=models.BooleanField(default=False, verbose_name='Airbag'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_bateria',
            field=models.BooleanField(default=False, verbose_name='Batería'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_check_engine',
            field=models.BooleanField(default=False, verbose_name='Check Engine'),
        ),
    ]
