# Generated by Django 6.1 on 2026-08-30 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_recepcionvehiculo_otros_testigos_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccionvehiculo',
            name='falla_reportada',
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='codigos_dtc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Códigos de Falla (DTC OBD2)'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_PROCESO', 'Diagnóstico en Proceso'), ('FINALIZADA', 'Inspección Finalizada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='motivo_ingreso',
            field=models.TextField(default=django.utils.timezone.now, help_text='Ej: Ruido en el motor, o Mantenimiento 10k', verbose_name='Motivo de Ingreso o Falla Reportada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones y Plan de Acción'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='tipo_inspeccion',
            field=models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Diagnóstico / Correctivo'), ('GARANTIA', 'Revisión por Garantía')], default='CORRECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='diagnostico_tecnico',
            field=models.TextField(blank=True, null=True, verbose_name='Hallazgos y Diagnóstico del Mecánico'),
        ),
    ]
