# Generated by Django 6.1 on 2026-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_remove_inspeccionvehiculo_falla_reportada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='motivo_ingreso',
            field=models.TextField(blank=True, help_text='Razón por la cual el cliente trae el vehículo', null=True, verbose_name='Motivo de Ingreso'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tipo_recepcion',
            field=models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Reparación Correctiva'), ('DIAGNOSTICO', 'Solo Diagnóstico / Escaneo'), ('ESTETICA', 'Enderezada, Pintura o Detailing'), ('GARANTIA', 'Garantía / Retorno')], default='DIAGNOSTICO', max_length=20, verbose_name='Tipo de Recepción'),
        ),
    ]
