# Generated by Django 6.1 on 2026-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_recepcionvehiculo_motivo_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_temperatura',
            field=models.BooleanField(default=False, verbose_name='Temperatura / Refrigerante'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_temperatura',
            field=models.BooleanField(default=False, verbose_name='Temperatura / Refrigerante'),
        ),
    ]
