# Generated by Django 6.1 on 2026-08-31 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_inspeccionvehiculo_testigo_temperatura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='aceptacion_condiciones',
            field=models.BooleanField(default=False, help_text='Indica si el cliente aceptó las condiciones de recepción y estado del vehículo', verbose_name='Aceptación de condiciones'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='fecha_firma_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de firma del cliente'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='fecha_firma_receptor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de firma del receptor'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='firma_cliente',
            field=models.TextField(blank=True, help_text='Firma digital del cliente aceptando la recepción (base64)', null=True, verbose_name='Firma del cliente'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='firma_receptor',
            field=models.TextField(blank=True, help_text='Firma digital del empleado que recibió el vehículo (base64)', null=True, verbose_name='Firma del receptor'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='recibido_por',
            field=models.ForeignKey(blank=True, help_text='Empleado que realizó la recepción del vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
    ]
