# Generated by Django 6.1 on 2026-09-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_recepcionvehiculo_aceptacion_condiciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='tipo_inspeccion',
            field=models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Reparación Correctiva'), ('DIAGNOSTICO', 'Solo Diagnóstico / Escaneo'), ('ESTETICA', 'Enderezada, Pintura o Detailing'), ('GARANTIA', 'Garantía / Retorno')], default='DIAGNOSTICO', max_length=20),
        ),
    ]
