# Generated by Django 6.1 on 2026-09-01 04:37

from django.db import migrations, models


def eliminar_inspecciones_duplicadas(apps, schema_editor):
    InspeccionVehiculo = apps.get_model('ordenes', 'InspeccionVehiculo')
    for inspeccion in InspeccionVehiculo.objects.filter(recepcion__isnull=False).order_by('-created_at'):
        duplicates = InspeccionVehiculo.objects.filter(
            recepcion_id=inspeccion.recepcion_id,
        ).exclude(pk=inspeccion.pk)
        duplicates.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('ordenes', '0014_alter_inspeccionvehiculo_tipo_inspeccion'),
    ]

    operations = [
        migrations.RunPython(eliminar_inspecciones_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inspeccionvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('recepcion__isnull', False)), fields=('recepcion',), name='una_inspeccion_por_recepcion'),
        ),
    ]
