# Generated by Django 6.1 on 2026-09-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_taller_ciudad'),
        ('ordenes', '0015_inspeccionvehiculo_una_inspeccion_por_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se realizó la inspección (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='empresas.taller', verbose_name='Sucursal / Taller'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se atiende la orden (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='empresas.taller', verbose_name='Sucursal / Taller'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde ingresó el vehículo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='empresas.taller', verbose_name='Sucursal / Taller'),
        ),
    ]
