# Generated by Django 6.1 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_inspeccionvehiculo_sucursal_ordentrabajo_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotorecepcion',
            options={'ordering': ['tipo_vista', 'created_at'], 'verbose_name': 'Foto de la Recepción', 'verbose_name_plural': 'Fotos de las Recepciones'},
        ),
        migrations.AddField(
            model_name='fotorecepcion',
            name='tipo_vista',
            field=models.CharField(choices=[('FRONTAL', 'Frontal'), ('LATERAL_IZQ', 'Lateral Izquierda'), ('LATERAL_DER', 'Lateral Derecha'), ('POSTERIOR', 'Posterior'), ('TABLERO', 'Tablero / Kilometraje')], default='FRONTAL', max_length=30, verbose_name='Vista fotográfica'),
        ),
    ]
