# Generated by Django 6.1 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_alter_fotorecepcion_options_fotorecepcion_tipo_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotorecepcion',
            name='tipo_vista',
            field=models.CharField(choices=[('FRONTAL', 'Frontal'), ('LATERAL_IZQ', 'Lateral Izquierda'), ('LATERAL_DER', 'Lateral Derecha'), ('POSTERIOR', 'Posterior'), ('TABLERO', 'Tablero / Kilometraje')], max_length=30, verbose_name='Vista fotográfica'),
        ),
    ]
