# Generated by Django 6.1 on 2026-09-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_taller_options_alter_taller_codigo_sucursal_and_more'),
        ('ordenes', '0018_alter_fotorecepcion_tipo_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Taller donde se realizó la inspección (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='empresas.taller', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Taller donde se atiende la orden (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='empresas.taller', verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Taller donde ingresó el vehículo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='empresas.taller', verbose_name='Taller'),
        ),
    ]
