# Generated by Django 6.1 on 2026-09-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_alter_inspeccionvehiculo_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Firma'), ('ACEPTADA', 'Aceptada y Firmada'), ('NO_ACEPTADA', 'No Aceptada / Sin Firma')], default='PENDIENTE', help_text='Estado de la recepción respecto a la firma y aceptación del cliente', max_length=20, verbose_name='Estado de la recepción'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='motivo_no_recepcion',
            field=models.TextField(blank=True, help_text='Observaciones cuando el cliente no aceptó las condiciones, no firmó o decidió no dejar el vehículo', null=True, verbose_name='Motivo de no recepción'),
        ),
    ]
