# Generated by Django 6.1 on 2026-09-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0020_recepcionvehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='kilometraje_ingreso',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional cuando el cliente no deja el vehículo', null=True, verbose_name='Kilometraje de Ingreso'),
        ),
    ]
