# Generated by Django 6.1 on 2026-09-05 23:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ordenes', '0021_alter_recepcionvehiculo_kilometraje_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRepuestoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Repuesto sugerido')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Cantidad estimada')),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor referencial del catálogo; no fija precio comercial ni descuenta stock.', max_digits=10, verbose_name='Precio referencial')),
                ('es_sugerido', models.BooleanField(default=True, help_text='Marcado como recomendación del diagnóstico inicial', verbose_name='Es sugerido')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_sugeridos', to='ordenes.inspeccionvehiculo')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_inspeccion', to='inventario.repuesto', verbose_name='Repuesto del catálogo')),
            ],
            options={
                'verbose_name': 'Detalle de Repuesto en Inspección',
                'verbose_name_plural': 'Detalles de Repuestos en Inspecciones',
                'ordering': ['-prioridad', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Servicio / Mano de obra detectado')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Horas estimadas')),
                ('precio_referencial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor referencial del catálogo; no fija precio comercial.', max_digits=10, verbose_name='Precio referencial')),
                ('es_sugerido', models.BooleanField(default=True, help_text='Marcado como recomendación del diagnóstico inicial', verbose_name='Es sugerido')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_detectados', to='ordenes.inspeccionvehiculo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_inspeccion', to='inventario.servicio', verbose_name='Servicio del catálogo')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio en Inspección',
                'verbose_name_plural': 'Detalles de Servicios en Inspecciones',
                'ordering': ['-prioridad', 'created_at'],
            },
        ),
    ]
