# Generated by Django 6.1 on 2026-09-06 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('cotizaciones', '0004_cotizacion_sucursal_and_more'),
        ('empresas', '0006_taller_digitos_cotizacion_taller_digitos_inspeccion_and_more'),
        ('ordenes', '0022_detallerepuestoinspeccion_detalleservicioinspeccion'),
        ('vehiculos', '0007_update_imagen_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='numero_inspeccion',
            field=models.CharField(blank=True, help_text='Código secuencial asignado automáticamente desde el taller', max_length=20, null=True, verbose_name='Número de Inspección'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='numero_recepcion',
            field=models.CharField(blank=True, help_text='Código secuencial asignado automáticamente desde el taller', max_length=20, null=True, verbose_name='Número de Recepción'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(max_length=20, verbose_name='Número de OT'),
        ),
        migrations.AddConstraint(
            model_name='inspeccionvehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_inspeccion'), name='inspeccion_empresa_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_orden'), name='ot_empresa_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='recepcionvehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_recepcion'), name='recepcion_empresa_numero_unico'),
        ),
    ]
