# Generated by Django 6.1 on 2026-09-06 05:02

from django.db import migrations


def asignar_sucursal_y_numero(apps, schema_editor):
    """Relaciona los documentos existentes con un taller y les asigna su número secuencial.

    - Recepciones e inspecciones sin `numero_*` reciben el número secuencial del taller
      (el primer taller activo de la empresa, o el que ya tengan vinculado).
    - Inspecciones sin taller heredan el de su recepción cuando existe.
    - Órdenes de trabajo sin taller solo se vinculan (conservan su número actual).
    """
    Taller = apps.get_model('empresas', 'Taller')
    RecepcionVehiculo = apps.get_model('ordenes', 'RecepcionVehiculo')
    InspeccionVehiculo = apps.get_model('ordenes', 'InspeccionVehiculo')
    OrdenTrabajo = apps.get_model('ordenes', 'OrdenTrabajo')

    def _resolver_taller(doc, preferido=None):
        if preferido is not None:
            return preferido
        if doc.sucursal_id:
            return Taller.objects.filter(pk=doc.sucursal_id, is_active=True).first()
        if doc.empresa_id:
            return (
                Taller.objects.filter(empresa_id=doc.empresa_id, is_active=True)
                .order_by('id')
                .first()
            )
        return None

    def _generar_y_numera(queryset, numero_field, prefijo_field, siguiente_field, digitos_field, preferido_fn=None):
        for doc in queryset.order_by('created_at', 'id'):
            taller = _resolver_taller(doc, preferido_fn(doc) if preferido_fn else None)
            if taller is None:
                continue

            prefijo = (getattr(taller, prefijo_field) or '').strip()
            siguiente = max(int(getattr(taller, siguiente_field) or 1), 1)
            digitos = max(int(getattr(taller, digitos_field) or 5), 1)

            setattr(taller, siguiente_field, siguiente + 1)
            taller.save(update_fields=[siguiente_field])

            if doc.sucursal_id is None:
                doc.sucursal_id = taller.pk
            setattr(doc, numero_field, f'{prefijo}{siguiente:0{digitos}d}')
            doc.save(update_fields=[numero_field, 'sucursal'])

    _generar_y_numera(
        RecepcionVehiculo.objects.filter(numero_recepcion__isnull=True, is_active=True),
        'numero_recepcion',
        'prefijo_recepcion',
        'siguiente_recepcion',
        'digitos_recepcion',
    )

    def _preferir_recepcion(doc):
        if doc.recepcion_id and doc.recepcion.sucursal_id:
            return Taller.objects.filter(pk=doc.recepcion.sucursal_id, is_active=True).first()
        return None

    _generar_y_numera(
        InspeccionVehiculo.objects.filter(numero_inspeccion__isnull=True, is_active=True),
        'numero_inspeccion',
        'prefijo_inspeccion',
        'siguiente_inspeccion',
        'digitos_inspeccion',
        preferido_fn=_preferir_recepcion,
    )

    # Órdenes de trabajo: solo se vinculan al taller (no se regeneran números).
    for ot in OrdenTrabajo.objects.filter(sucursal__isnull=True):
        taller = _resolver_taller(ot)
        if taller:
            ot.sucursal = taller
            ot.save(update_fields=['sucursal'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0023_inspeccionvehiculo_numero_inspeccion_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_sucursal_y_numero, reverse_code=migrations.RunPython.noop),
    ]