# Generated by Django 6.1 on 2026-09-06 05:03

from django.db import migrations


def asignar_numero_recepciones(apps, schema_editor):
    """Numera las recepciones que quedaron pendientes.

    La migración 0024 solo procesó documentos activos; las recepciones visibles
    en el listado (incluidas las marcadas como eliminadas lógicamente) seguían
    sin número ni taller. Aquí se asignan los pendientes usando el taller por
    defecto de la empresa.
    """
    Taller = apps.get_model('empresas', 'Taller')
    RecepcionVehiculo = apps.get_model('ordenes', 'RecepcionVehiculo')

    for recepcion in (
        RecepcionVehiculo.objects.filter(numero_recepcion__isnull=True)
        .order_by('created_at', 'id')
    ):
        taller = None
        if recepcion.sucursal_id:
            taller = Taller.objects.filter(pk=recepcion.sucursal_id, is_active=True).first()
        elif recepcion.empresa_id:
            taller = (
                Taller.objects.filter(empresa_id=recepcion.empresa_id, is_active=True)
                .order_by('id')
                .first()
            )
        if taller is None:
            continue

        prefijo = (getattr(taller, 'prefijo_recepcion') or '').strip()
        siguiente = max(int(getattr(taller, 'siguiente_recepcion') or 1), 1)
        digitos = max(int(getattr(taller, 'digitos_recepcion') or 5), 1)

        setattr(taller, 'siguiente_recepcion', siguiente + 1)
        taller.save(update_fields=['siguiente_recepcion'])

        if recepcion.sucursal_id is None:
            recepcion.sucursal_id = taller.pk
        recepcion.numero_recepcion = f'{prefijo}{siguiente:0{digitos}d}'
        recepcion.save(update_fields=['numero_recepcion', 'sucursal'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_backfill_sucursal_numero'),
    ]

    operations = [
        migrations.RunPython(asignar_numero_recepciones, reverse_code=migrations.RunPython.noop),
    ]