# Generated by Django 6.1 on 2026-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_backfill_numero_recepciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_presion_llantas',
            field=models.BooleanField(default=False, verbose_name='Presión de Llantas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_presion_llantas',
            field=models.BooleanField(default=False, verbose_name='Presión de Llantas'),
        ),
    ]
