# Generated by Django 6.1 on 2026-09-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_testigo_presion_llantas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_antiniebla_traseras',
            field=models.BooleanField(default=False, verbose_name='Luces Antiniebla Traseras'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_bujias_precalentamiento',
            field=models.BooleanField(default=False, verbose_name='Bujías de Precalentamiento'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_cinturon',
            field=models.BooleanField(default=False, verbose_name='Cinturón Desabrochado'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_combustible_bajo',
            field=models.BooleanField(default=False, verbose_name='Nivel Bajo de Combustible'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_desempanado',
            field=models.BooleanField(default=False, verbose_name='Desempañado del Parabrisas'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_esp',
            field=models.BooleanField(default=False, verbose_name='Control de Estabilidad (ESP)'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_freno_estacionamiento',
            field=models.BooleanField(default=False, verbose_name='Freno de Estacionamiento'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_frenos_fallo',
            field=models.BooleanField(default=False, verbose_name='Fallo en el Sistema de Frenos'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_limpiaparabrisas',
            field=models.BooleanField(default=False, verbose_name='Limpiaparabrisas'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_luces_emergencia',
            field=models.BooleanField(default=False, verbose_name='Luces de Emergencia'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_luces_largas',
            field=models.BooleanField(default=False, verbose_name='Luces Largas'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_pedal_freno',
            field=models.BooleanField(default=False, verbose_name='Pedal de Freno'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='testigo_puerta_maletero',
            field=models.BooleanField(default=False, verbose_name='Puerta o Maletero Abierto'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_antiniebla_traseras',
            field=models.BooleanField(default=False, verbose_name='Luces Antiniebla Traseras'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_bujias_precalentamiento',
            field=models.BooleanField(default=False, verbose_name='Bujías de Precalentamiento'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_cinturon',
            field=models.BooleanField(default=False, verbose_name='Cinturón Desabrochado'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_combustible_bajo',
            field=models.BooleanField(default=False, verbose_name='Nivel Bajo de Combustible'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_desempanado',
            field=models.BooleanField(default=False, verbose_name='Desempañado del Parabrisas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_esp',
            field=models.BooleanField(default=False, verbose_name='Control de Estabilidad (ESP)'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_freno_estacionamiento',
            field=models.BooleanField(default=False, verbose_name='Freno de Estacionamiento'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_frenos_fallo',
            field=models.BooleanField(default=False, verbose_name='Fallo en el Sistema de Frenos'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_limpiaparabrisas',
            field=models.BooleanField(default=False, verbose_name='Limpiaparabrisas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_luces_emergencia',
            field=models.BooleanField(default=False, verbose_name='Luces de Emergencia'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_luces_largas',
            field=models.BooleanField(default=False, verbose_name='Luces Largas'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_pedal_freno',
            field=models.BooleanField(default=False, verbose_name='Pedal de Freno'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='testigo_puerta_maletero',
            field=models.BooleanField(default=False, verbose_name='Puerta o Maletero Abierto'),
        ),
    ]
