# Generated by Django 6.1 on 2026-09-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0027_testigos_adicionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/inspeccion_fotos/')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.inspeccionvehiculo', verbose_name='Inspección')),
            ],
            options={
                'verbose_name': 'Foto de Inspección',
                'verbose_name_plural': 'Fotos de Inspecciones',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
