# Generated by Django 6.1 on 2026-09-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0028_fotoinspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerepuestoinspeccion',
            name='es_sugerido',
            field=models.BooleanField(default=False, help_text='Indica si es una recomendación opcional; por defecto es necesario/obligatorio', verbose_name='Es sugerido'),
        ),
        migrations.AlterField(
            model_name='detalleservicioinspeccion',
            name='es_sugerido',
            field=models.BooleanField(default=False, help_text='Indica si es una recomendación opcional; por defecto es necesario/obligatorio', verbose_name='Es sugerido'),
        ),
    ]
