# Generated by Django 6.1 on 2026-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_alter_detallerepuestoinspeccion_es_sugerido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionvehiculo',
            name='tipo_inspeccion',
            field=models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Revisión Correctiva'), ('DIAGNOSTICO', 'Diagnóstico'), ('ESTETICA', 'Evaluación Estética'), ('GARANTIA', 'Revisión por Garantía')], default='DIAGNOSTICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('NO_ACEPTADA', 'Rechazada')], default='PENDIENTE', help_text='Estado de la recepción respecto a la firma y aceptación del cliente', max_length=20, verbose_name='Estado de la recepción'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tipo_recepcion',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REPARACIÓN', 'Reparación'), ('DIAGNOSTICO', 'Diagnóstico'), ('ESTETICA', 'Estética'), ('GARANTIA', 'Garantía'), ('SINISTRO', 'Siniestro'), ('OTRO', 'Otro')], default='PENDIENTE', max_length=20, verbose_name='Tipo de Recepción'),
        ),
    ]
