# Generated by Django 6.1 on 2026-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_fotoordentrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoordentrabajo',
            name='imagen',
            field=models.ImageField(upload_to='ordenes/orden_fotos/'),
        ),
    ]
