# Generated by Django 6.1 on 2026-09-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0032_alter_fotoordentrabajo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='fecha_firma_receptor',
        ),
        migrations.RemoveField(
            model_name='recepcionvehiculo',
            name='firma_receptor',
        ),
    ]
