# Generated by Django 6.1 on 2026-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0033_remove_recepcionvehiculo_fecha_firma_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='ajustador_nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre del ajustador'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='ajustador_telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono del ajustador'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='cantidad_llaves',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cantidad de llaves del vehículo entregadas por el cliente', verbose_name='Cantidad de llaves'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='compania_seguro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Compañía de seguro'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de póliza'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='numero_reclamo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de reclamo / siniestro'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_billetera',
            field=models.BooleanField(default=False, verbose_name='Billetera'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_celular',
            field=models.BooleanField(default=False, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_dinero',
            field=models.BooleanField(default=False, verbose_name='Dinero en efectivo'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_documentos',
            field=models.BooleanField(default=False, verbose_name='Documentos personales'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_equipaje',
            field=models.BooleanField(default=False, verbose_name='Equipaje / Bolsos'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_gafas',
            field=models.BooleanField(default=False, verbose_name='Gafas / Lentes'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencia_otros',
            field=models.BooleanField(default=False, verbose_name='Otros objetos de valor'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='pertenencias_observaciones',
            field=models.CharField(blank=True, help_text='Detalles adicionales sobre objetos de valor dejados en el vehículo', max_length=255, null=True, verbose_name='Observaciones de pertenencias'),
        ),
        migrations.AddField(
            model_name='recepcionvehiculo',
            name='tiene_llave_control',
            field=models.BooleanField(default=False, verbose_name='Llave de control / Control remoto'),
        ),
    ]
