# Generated by Django 6.1 on 2026-09-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('ordenes', '0034_recepcionvehiculo_ajustador_nombre_and_more'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente asociado cuando la inspección no proviene de una recepción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Vehículo asociado cuando la inspección no proviene de una recepción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='vehiculos.vehiculo'),
        ),
    ]
