# Generated by Django 6.1 on 2026-09-17 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0035_inspeccionvehiculo_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Mecánico o técnico responsable de la inspección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
