# Generated by Django 6.1 on 2026-09-27 04:36

import django.utils.timezone
from django.db import migrations, models


def sembrar_fechas(apps, schema_editor):
    """Las inspecciones históricas usaban created_at/updated_at como referencia."""
    InspeccionVehiculo = apps.get_model('ordenes', 'InspeccionVehiculo')

    InspeccionVehiculo.objects.filter(estado='FINALIZADA').update(
        fecha_inspeccion=models.F('created_at'),
        fecha_finalizacion=models.F('updated_at'),
    )
    InspeccionVehiculo.objects.exclude(estado='FINALIZADA').update(
        fecha_inspeccion=models.F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0037_unificar_tipos_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Se registra automáticamente al finalizar la inspección y se limpia al reabrirla', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='fecha_inspeccion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Momento real en que se realizó (o se inició) el diagnóstico', verbose_name='Fecha de inspección'),
        ),
        migrations.RunPython(sembrar_fechas, migrations.RunPython.noop),
    ]
