# Generated by Django 6.1 on 2026-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0038_inspeccion_fechas_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='kilometraje_diagnostico',
            field=models.PositiveIntegerField(blank=True, help_text='Lectura del odómetro al momento del diagnóstico, después de la prueba de ruta si la hubo', null=True, verbose_name='Kilometraje de diagnóstico'),
        ),
    ]
