# Generated by Django 6.1 on 2026-09-28 02:44

from django.db import migrations, models


def backfill_ingresado_a_pendiente(apps, schema_editor):
    OrdenTrabajo = apps.get_model('ordenes', 'OrdenTrabajo')
    OrdenTrabajo.objects.filter(estado='INGRESADO').update(estado='PENDIENTE')


def deshacer_pendiente_a_ingresado(apps, schema_editor):
    OrdenTrabajo = apps.get_model('ordenes', 'OrdenTrabajo')
    OrdenTrabajo.objects.filter(estado='PENDIENTE').update(estado='INGRESADO')


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0039_inspeccionvehiculo_kilometraje_diagnostico'),
    ]

    operations = [
        migrations.RunPython(backfill_ingresado_a_pendiente, deshacer_pendiente_a_ingresado),
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_espera',
            field=models.CharField(blank=True, help_text='Razón de la espera cuando la orden está pausada (repuestos, aprobación del cliente, trabajo adicional, etc.)', max_length=80, null=True, verbose_name='Motivo de espera'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de inicio'), ('EN_ESPERA', 'En espera (repuestos / aprobación)'), ('EN_PROCESO', 'En Trabajo / Ejecución'), ('COMPLETADO', 'Trabajo Listo'), ('ENTREGADO', 'Entregado y Cerrado'), ('CANCELADO', 'Anulado / Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
