# Generated by Django 6.1 on 2026-09-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0040_ordentrabajo_motivo_espera_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En espera'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
    ]
