# Generated by Django 6.1 on 2026-09-28 16:38

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models

DOS = Decimal('0.01')


def _bruto(servicio=None, repuesto=None):
    if servicio is not None:
        return Decimal(servicio.horas_aplicadas) * Decimal(servicio.precio_unitario)
    return Decimal(repuesto.cantidad) * Decimal(repuesto.precio_unitario)


def backfill_impuestos_ordenes(apps, schema_editor):
    """Recalcula las OT existentes con el esquema de impuestos por línea.

    - El descuento que vivía en la cabecera se reparte entre las líneas
      (proporcional al bruto) para no alterar los totales históricos.
    - Cada línea queda con `monto_iva` calculado al 15% (IVA uniforme previo).
    - Las cabeceras se recomputan con la fórmula nueva.
    """
    OrdenTrabajo = apps.get_model('ordenes', 'OrdenTrabajo')
    DetalleServicio = apps.get_model('ordenes', 'DetalleServicioOrdenTrabajo')
    DetalleRepuesto = apps.get_model('ordenes', 'DetalleRepuestoOrdenTrabajo')

    for orden in OrdenTrabajo.objects.all():
        servicios = list(orden.servicios.all())
        repuestos = list(orden.repuestos.all())

        lineas = [(det, _bruto(servicio=det)) for det in servicios]
        lineas += [(det, _bruto(repuesto=det)) for det in repuestos]

        descuento_cabecera = orden.descuento or Decimal('0.00')
        if descuento_cabecera > 0 and lineas:
            total_bruto = sum(bruto for _, bruto in lineas)
            if total_bruto > 0:
                asignado = Decimal('0.00')
                ultimo = len(lineas) - 1
                for indice, (det, bruto) in enumerate(lineas):
                    if indice == ultimo:
                        parte = descuento_cabecera - asignado
                    else:
                        parte = (descuento_cabecera * bruto / total_bruto).quantize(
                            DOS, rounding=ROUND_HALF_UP
                        )
                        asignado += parte
                    det.descuento = min(max(Decimal('0.00'), parte), bruto)

        for det, bruto in lineas:
            det.subtotal = max(Decimal('0.00'), bruto - det.descuento)
            det.monto_iva = (det.subtotal * det.iva_porcentaje).quantize(DOS)
            det.save(update_fields=['descuento', 'subtotal', 'monto_iva'])

        servicios = list(orden.servicios.all())
        repuestos = list(orden.repuestos.all())
        neto_serv = sum(det.subtotal for det in servicios)
        neto_rep = sum(det.subtotal for det in repuestos)
        orden.subtotal_servicios = neto_serv
        orden.subtotal_repuestos = neto_rep
        orden.descuento = sum(det.descuento for det in servicios) + sum(
            det.descuento for det in repuestos
        )
        orden.subtotal_neto = neto_serv + neto_rep
        orden.subtotal_base_0 = sum(
            det.subtotal for det in lineas_ok(servicios, repuestos) if det.iva_porcentaje == 0
        )
        orden.subtotal_base_gravada = sum(
            det.subtotal for det in lineas_ok(servicios, repuestos) if det.iva_porcentaje > 0
        )
        orden.monto_iva = sum(det.monto_iva for det in servicios) + sum(
            det.monto_iva for det in repuestos
        )
        orden.total = orden.subtotal_neto + orden.monto_iva
        orden.save(update_fields=[
            'subtotal_servicios', 'subtotal_repuestos', 'descuento', 'subtotal_neto',
            'subtotal_base_0', 'subtotal_base_gravada', 'monto_iva', 'total', 'updated_at',
        ])


def lineas_ok(servicios, repuestos):
    return list(servicios) + list(repuestos)


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0041_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerepuestoordentrabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detallerepuestoordentrabajo',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detallerepuestoordentrabajo',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleservicioordentrabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleservicioordentrabajo',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleservicioordentrabajo',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas visibles para el cliente', null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='subtotal_base_0',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='subtotal_base_gravada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(backfill_impuestos_ordenes, migrations.RunPython.noop),
    ]
