# Generated by Django 6.1 on 2026-09-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0042_detallerepuestoordentrabajo_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='observaciones_internas',
        ),
    ]
