# Generated by Django 6.1 on 2026-10-04 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_identificacion'),
        ('cotizaciones', '0017_numero_por_sucursal'),
        ('empresas', '0007_taller_capacidad_citas_dia_and_more'),
        ('ordenes', '0043_remove_ordentrabajo_observaciones_internas'),
        ('vehiculos', '0008_vehiculo_proxima_mantenimiento_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspeccionvehiculo',
            name='inspeccion_empresa_numero_unico',
        ),
        migrations.RemoveConstraint(
            model_name='ordentrabajo',
            name='ot_empresa_numero_unico',
        ),
        migrations.RemoveConstraint(
            model_name='recepcionvehiculo',
            name='recepcion_empresa_numero_unico',
        ),
        migrations.AddConstraint(
            model_name='inspeccionvehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'numero_inspeccion'), name='inspeccion_empresa_sucursal_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'numero_orden'), name='ot_empresa_sucursal_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='recepcionvehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'sucursal', 'numero_recepcion'), name='recepcion_empresa_sucursal_numero_unico'),
        ),
    ]
