# Generated by Django 6.1 on 2026-10-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0044_numero_por_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_antena',
            field=models.BooleanField(default=False, verbose_name='Antena'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_copas_ruedas',
            field=models.BooleanField(default=False, verbose_name='Copas / Tapacubos'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_espejo_derecho',
            field=models.BooleanField(default=False, verbose_name='Espejo Derecho'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_espejo_izquierdo',
            field=models.BooleanField(default=False, verbose_name='Espejo Izquierdo'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_faros_lunas',
            field=models.BooleanField(default=False, verbose_name='Faros / Lunas'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_gata_palanca',
            field=models.BooleanField(default=False, verbose_name='Gato y Palanca'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_llanta_repuesto',
            field=models.BooleanField(default=False, verbose_name='Llanta de Refacción / Repuesto'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_placas',
            field=models.BooleanField(default=False, verbose_name='Placas de Circulación'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_radio',
            field=models.BooleanField(default=False, verbose_name='Radio / Mascarilla'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_tapa_gasolina',
            field=models.BooleanField(default=False, verbose_name='Tapa de Gasolina'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_tapetes',
            field=models.BooleanField(default=False, verbose_name='Tapetes / Alfombras'),
        ),
        migrations.AlterField(
            model_name='recepcionvehiculo',
            name='tiene_vidrios',
            field=models.BooleanField(default=False, verbose_name='Vidrios / Cristales'),
        ),
    ]
