# Generated by Django 6.1 on 2026-08-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('placa', models.CharField(help_text='Ejemplo: PBA1234 (Sin guiones)', max_length=10, unique=True, verbose_name='Placa')),
                ('vin', models.CharField(blank=True, default='', max_length=17, verbose_name='Número de Chasis / VIN')),
                ('numero_motor', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Motor')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('color', models.CharField(blank=True, default='', max_length=30, verbose_name='Color')),
                ('transmision', models.CharField(choices=[('M', 'Manual / Mecánica'), ('A', 'Automática'), ('C', 'CVT')], default='M', max_length=1, verbose_name='Transmisión')),
                ('tipo_combustible', models.CharField(choices=[('GAS', 'Gasolina'), ('DIE', 'Diésel'), ('HIB', 'Híbrido'), ('ELE', 'Eléctrico')], default='GAS', max_length=3, verbose_name='Tipo de Combustible')),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, verbose_name='Kilometraje Actual')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente', verbose_name='Propietario / Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
