# Generated by Django 6.1 on 2026-08-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_combustible',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('GAS', 'Gasolina'), ('DIE', 'Diésel'), ('HIB', 'Híbrido'), ('ELE', 'Eléctrico')], default='GAS', max_length=3),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('M', 'Manual / Mecánica'), ('A', 'Automática'), ('C', 'CVT')], default='M', max_length=1),
        ),
    ]
