# Generated by Django 6.1 on 2026-08-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_unique_cliente_per_empresa'),
        ('vehiculos', '0002_remove_vehiculo_tipo_combustible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cliente',
        ),
        migrations.CreateModel(
            name='VehiculoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue deshabilitado/eliminado lógicamente', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('es_actual', models.BooleanField(default=True, verbose_name='¿Es el dueño activo?')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_asociados', to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Relación Vehículo-Propietario',
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_actual', True)), fields=('vehiculo', 'cliente'), name='unique_vehiculo_cliente_activo')],
            },
        ),
    ]
