# Generated by Django 6.1 on 2026-08-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo'),
        ('vehiculos', '0003_remove_vehiculo_cliente_vehiculopropietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='vehiculos', to='empresas.empresa', verbose_name='Empresas'),
        ),
    ]
