# Generated by Django 6.1 on 2026-08-23 18:20

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_add_vehiculo_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='pais_origen',
            field=django_countries.fields.CountryField(default='EC', help_text='País de fabricación o procedencia original', max_length=2),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AUTO', 'Automóvil'), ('JEEP', 'Jeep'), ('CAMN', 'Camioneta'), ('MOTO', 'Motocicleta'), ('MTNA', 'Motoneta'), ('TRIC', 'Tricimoto'), ('CUAT', 'Cuatrimoto'), ('BUS', 'Bus / Autobús'), ('BUSE', 'Buseta'), ('MICR', 'Microbús / Furgoneta'), ('CAMI', 'Camión'), ('TRAC', 'Tractocamión'), ('VOLQ', 'Volqueta'), ('FURG', 'Furgón'), ('REMO', 'Remolque / Semirremolque'), ('MAGR', 'Maquinaria Agrícola'), ('MCAM', 'Maquinaria Caminera')], default='AUTO', max_length=4),
        ),
    ]
