# Generated by Django 6.1 on 2026-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_pais_origen_vehiculo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP. Máximo 2MB.', null=True, upload_to='vehiculos/%Y/%m/%d', verbose_name='Imagen del Vehículo'),
        ),
    ]
