# Generated by Django 6.1 on 2026-08-25 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_add_vehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Año de Fabricación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('GAS', 'Gasolina'), ('DIE', 'Diésel'), ('HIB', 'Híbrido'), ('ELE', 'Eléctrico'), ('GNV', 'Gas Natural Vehicular (GNV)')], default='GAS', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP. Máximo 2MB. Se optimiza automáticamente.', null=True, upload_to='vehiculos/%Y/%m/%d', verbose_name='Imagen del Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AUTO', 'Automóvil'), ('JEEP', 'Jeep'), ('CAMN', 'Camioneta'), ('MOTO', 'Motocicleta'), ('MTNA', 'Motoneta'), ('TRIC', 'Tricimoto'), ('CUAT', 'Cuatrimoto'), ('BUS', 'Bus / Autobús'), ('BUSE', 'Buseta'), ('MICR', 'Microbús / Furgoneta'), ('CAMI', 'Camión'), ('TRAC', 'Tractocamión'), ('VOLQ', 'Volqueta'), ('FURG', 'Furgón'), ('REMO', 'Remolque / Semirremolque'), ('MAGR', 'Maquinaria Agrícola'), ('MCAM', 'Maquinaria Caminera')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número de Chasis / VIN'),
        ),
    ]
