# Generated by Django 6.1 on 2026-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_update_imagen_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='proxima_mantenimiento_fecha',
            field=models.DateField(blank=True, help_text='Fecha estimada del siguiente mantenimiento preventivo. Se usa para recordatorios por WhatsApp.', null=True, verbose_name='Próximo mantenimiento (fecha)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proximo_mantenimiento_km',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje en el que corresponde el siguiente mantenimiento preventivo. Se usa para recordatorios por WhatsApp.', null=True, verbose_name='Próximo mantenimiento (km)'),
        ),
    ]
